version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mentalcare-db
    environment:
      POSTGRES_DB: mentalcare
      POSTGRES_USER: mentalcare_user
      POSTGRES_PASSWORD: mentalcare_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mentalcare_user -d mentalcare"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: